version: '3.8'
services:
  ocr_test:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./:/workspace"
    # ports:
    #   - "3000:3000"
    tty: true
    # command: sh -c "npm start"
