version: '3.8'
services:
  ocr_server:
    build:
      context: ./
      dockerfile: ./ocrServer/Dockerfile
    volumes:
      - "./ocrServer:/workspace"
    ports:
      - "5000:5000"
    tty: true
    # command: flask --app main run
